[package]
name = "rumple-s-adventures"
version = "0.1.0"
authors = ["grzi <jeremy.thulliez@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.3"
log = "0.4.11"

[features]
default = ["metal"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

